/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        serif: ['"Newsreader"', '"Instrument Serif"', '"Cormorant Garamond"', 'Georgia', 'serif'],
        display: ['"Newsreader"', '"Instrument Serif"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', '"SF Mono"', 'Consolas', 'monospace'],
      },
      colors: {
        'kroma-paper': '#F5F2EB',
        'kroma-paper-light': '#FAF9F5',
        'kroma-card': '#F8F6F0',
        'kroma-ink': '#151513',
        'kroma-black': '#0D0D0C',
        'kroma-gray': '#69665F',
        'kroma-muted': '#8E8A81',
        'kroma-white': '#F8F6EF',
        'kroma-dark': '#11110F',
        canvas: 'var(--bg-canvas)',
        'surface-1': 'var(--bg-surface-1)',
        'surface-2': 'var(--bg-surface-2)',
        'surface-3': 'var(--bg-surface-3)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
      },
      borderRadius: {
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'full': '9999px',
        'pill': '22px',
      },
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
      },
    },
  },
  plugins: [],
}
