/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"General Sans"', '"Plus Jakarta Sans"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        serif: ['"Instrument Serif"', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', '"SF Mono"', 'Consolas', 'monospace'],
      },
      colors: {
        canvas: 'var(--bg-canvas)',
        'surface-1': 'var(--bg-surface-1)',
        'surface-2': 'var(--bg-surface-2)',
        'surface-3': 'var(--bg-surface-3)',
        'surface-elevated': 'var(--bg-surface-elevated)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-inverse': 'var(--text-inverse)',
        'border-subtle': 'var(--border-subtle)',
        'border-medium': 'var(--border-medium)',
        'border-strong': 'var(--border-strong)',
        'accent-gold': 'var(--accent-gold)',
        'accent-blue': 'var(--accent-blue)',
        kroma: {
          bg: 'var(--bg-canvas)',
          background: 'var(--bg-canvas)',
          surface: 'var(--bg-surface-1)',
          card: 'var(--bg-surface-1)',
          foreground: 'var(--text-primary)',
          text: 'var(--text-primary)',
          muted: 'var(--text-secondary)',
          border: 'var(--border-medium)',
          subtle: 'var(--border-subtle)',
          ring: 'var(--color-primary)',
          red: '#FF3B30',
          orange: '#FF9500',
          yellow: '#FFD60A',
          green: '#34C759',
          blue: '#00AEEF',
          purple: '#7B2CBF',
        },
      },
      borderRadius: {
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'lg': '10px',
      },
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
      },
      keyframes: {
        pinPulse: {
          '0%, 100%': { transform: 'translate(-50%, -50%) scale(1)' },
          '50%': { transform: 'translate(-50%, -50%) scale(1.15)' },
        },
        statementRollerRock: {
          '0%, 100%': { transform: 'rotate(-8deg)' },
          '25%, 75%': { transform: 'rotate(0deg)' },
          '50%': { transform: 'rotate(8deg)' },
        },
      },
      animation: {
        'pin-pulse': 'pinPulse 2s ease-in-out infinite',
        'roller-rock': 'statementRollerRock 1.5s cubic-bezier(0.65, 0, 0.35, 1) infinite',
      },
    },
  },
  plugins: [],
}
