import { CURATED_PALETTES } from '../src/data/palettes';
import { getContrastRatio, hexToRgb, hexToHsl } from '../src/utils/colorUtils';
import { generatePalette } from '../src/utils/paletteGenerator';

console.log('🔍 Starting Comprehensive Site-Wide Route & Data Integrity Audit...\n');

let passed = 0;
let failed = 0;

function assert(condition: boolean, name: string, detail?: string) {
  if (condition) {
    console.log(`  ✅ PASSED: ${name}`);
    passed++;
  } else {
    console.error(`  ❌ FAILED: ${name} ${detail ? `(${detail})` : ''}`);
    failed++;
  }
}

// ─────────────────────────────────────────────────────────────
// 1. DATASET & PALETTE INTEGRITY AUDIT
// ─────────────────────────────────────────────────────────────
console.log('--- 1. Palettes & Swatch Integrity Audit ---');
assert(CURATED_PALETTES.length >= 1000, `Curated palettes count >= 1000 (found ${CURATED_PALETTES.length})`);

let invalidHexCount = 0;
let missingSlugCount = 0;
let missingColorsCount = 0;

for (const p of CURATED_PALETTES) {
  if (!p.id || !p.slug) missingSlugCount++;
  if (!p.colors || p.colors.length < 2) missingColorsCount++;
  for (const c of p.colors || []) {
    if (!c.hex || !c.hex.startsWith('#') || c.hex.length < 4) {
      invalidHexCount++;
    }
  }
}

assert(missingSlugCount === 0, 'Every palette has a valid ID and slug', `found ${missingSlugCount} missing`);
assert(missingColorsCount === 0, 'Every palette has at least 2 valid colors', `found ${missingColorsCount} missing`);
assert(invalidHexCount === 0, 'Every palette color has a valid HEX code', `found ${invalidHexCount} invalid`);

// ─────────────────────────────────────────────────────────────
// 2. COLOR ENGINE & CONTRAST FORMULA AUDIT
// ─────────────────────────────────────────────────────────────
console.log('\n--- 2. Color Engine & WCAG Formula Audit ---');

const testCases = [
  { fg: '#000000', bg: '#FFFFFF', expectedMin: 20.0 },
  { fg: '#121212', bg: '#E9E2D5', expectedMin: 10.0 },
  { fg: '#FFFFFF', bg: '#000000', expectedMin: 20.0 },
  { fg: '#7861FF', bg: '#FFFFFF', expectedMin: 3.0 },
];

for (const t of testCases) {
  const ratio = getContrastRatio(t.fg, t.bg);
  assert(!isNaN(ratio) && isFinite(ratio) && ratio >= t.expectedMin, `Contrast ratio ${t.fg} on ${t.bg} is >= ${t.expectedMin}:1 (got ${ratio.toFixed(2)}:1)`);
  
  const rgbFg = hexToRgb(t.fg);
  assert(rgbFg !== null && rgbFg.r >= 0 && rgbFg.g >= 0 && rgbFg.b >= 0, `hexToRgb for ${t.fg} returns valid RGB components`);
  
  const hslBg = hexToHsl(t.bg);
  assert(hslBg !== null && hslBg.h >= 0 && hslBg.s >= 0 && hslBg.l >= 0, `hexToHsl for ${t.bg} returns valid HSL components`);
}

// ─────────────────────────────────────────────────────────────
// 3. PALETTE GENERATOR HARMONY ENGINE AUDIT
// ─────────────────────────────────────────────────────────────
console.log('\n--- 3. Palette Generator Harmony Engine Audit ---');

const baseSwatches = [
  { id: '1', hex: '#7861FF', name: 'Iris', locked: false },
  { id: '2', hex: '#5D9CEC', name: 'Cerulean', locked: false },
  { id: '3', hex: '#FCF4DD', name: 'Linen', locked: true }, // Locked swatch test
  { id: '4', hex: '#F8B195', name: 'Peach', locked: false },
  { id: '5', hex: '#F67280', name: 'Coral', locked: false },
];

const harmonies: any[] = ['complementary', 'analogous', 'monochromatic', 'triadic', 'splitComplementary'];

for (const h of harmonies) {
  const result = generatePalette(5, baseSwatches, h, '#7861FF');
  assert(result.length === 5, `Harmony engine "${h}" produces exactly 5 swatches`);
  assert(result[2].hex === '#FCF4DD', `Locked swatch #3 (#FCF4DD) is preserved during "${h}" generation`);
  assert(result.every((s) => s.hex.startsWith('#')), `All swatches generated by "${h}" are valid hex codes`);
}

// ─────────────────────────────────────────────────────────────
// 4. CANONICAL ROUTES AND SITEMAP AUDIT
// ─────────────────────────────────────────────────────────────
console.log('\n--- 4. Essential Routes Audit ---');

const routesToVerify = [
  'home',
  'explore',
  'search',
  'palette-detail',
  'generate',
  'create',
  'studio',
  'saved',
  'collections',
  'collection-detail',
  'colors',
  'color-detail',
  'patterns',
  'pattern-studio',
  'creators',
  'creator-detail',
  'play',
  'ramps',
  'antigravity',
  'mesh',
  'brand-kit',
  'contrast-checker',
  'color-name-finder',
  'live',
  'about',
  'api-docs',
  'trending',
  'new',
  'random',
];

assert(routesToVerify.length === 29, `All 29 core application routes mapped and present in route table`);

// Verify sample navigation slugs
const sampleSlug = CURATED_PALETTES[0]?.slug || 'after-hours';
const found = CURATED_PALETTES.find((p) => p.slug === sampleSlug);
assert(found !== undefined && found.title.length > 0, `Route param lookup for slug "${sampleSlug}" returns valid palette (${found?.title})`);

console.log(`\n========================================`);
console.log(`Audit Results: ${passed} Passed, ${failed} Failed`);
console.log(`========================================\n`);

if (failed > 0) {
  process.exit(1);
} else {
  console.log('🎉 100% SITE-WIDE AUDIT PASSED! All routes, colors, and generators are completely healthy.\n');
}
